### ISSUE TITLE
Error in Chapter 13 - Model.Derived Properties when using VS2010 under WinXP

### ISSUE THREAD

**Issue by grandtiger** [dmitry-a-morozov/fsharp-wpf-mvc-series#2]
Here is the error I got.
Error   1   The member or object constructor 'GetValue' does not take 1 argument(s). An overload was found taking 2 arguments.  C:\GitHub\fsharp-wpf-mvc-series\Chapter 13 - Model.Derived Properties\FSharp.Windows\Binding.fs 100 74  FSharp.Windows

However, it works fine on Win7 with VS2013.

**Comment by dmitry-a-morozov** [comment]
pull the latest .

**Comment by dmitry-a-morozov** [comment]
would you be interested in framework productization (nuget, decicated web site etc)?
